/* ============================================================================
   HDT · Hojas de Consumo — Esquema inicial
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   Ejecutar:  psql "<cadena-de-conexion>" -f 01_Esquema_HojaConsumo.sql
   ----------------------------------------------------------------------------
   IDEMPOTENTE y NO destructivo: se puede re-ejecutar sin borrar datos.
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS cat;
CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------------------------------------------------------------------------
   Roles de la aplicación (independientes del SSO de Microsoft)
   --------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS cat.Rol (
    Id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL UNIQUE
);
INSERT INTO cat.Rol (Nombre) VALUES ('Hospital'), ('Bodega'), ('Administrador')
    ON CONFLICT (Nombre) DO NOTHING;

/* Usuarios que han iniciado sesión y su rol. La identidad la administra Microsoft;
   aquí solo mapeamos correo -> rol. Un usuario nuevo entra como 'Hospital'. */
CREATE TABLE IF NOT EXISTS dbo.UsuarioRol (
    Email        VARCHAR(200) PRIMARY KEY,
    Nombre       VARCHAR(200),
    RolId        INT NOT NULL REFERENCES cat.Rol(Id),
    UltimoAcceso TIMESTAMP(0)
);

/* ---------------------------------------------------------------------------
   Hoja de consumo (ENCABEZADO)
   --------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo.HojaConsumo (
    Id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Datos del encabezado (extraídos de la hoja; el usuario puede corregirlos)
    NumeroHoja       VARCHAR(50)  NULL,   -- N° en la imagen de la hoja
    NumeroDocumento  VARCHAR(80)  NULL,
    Regimen          VARCHAR(60)  NULL,
    Paciente         VARCHAR(200) NULL,
    Identificacion   VARCHAR(60)  NULL,
    Tipo             VARCHAR(30)  NULL,   -- ej. R-T
    FechaAccidente   DATE NULL,
    FechaCirugia     DATE NULL,
    FechaHoja        DATE NULL,
    Cirujano         VARCHAR(200) NULL,
    Instrumentista   VARCHAR(200) NULL,
    Diagnostico      VARCHAR(400) NULL,
    Procedimiento    VARCHAR(400) NULL,

    -- Imagen original de la hoja (base64) y su tipo MIME
    ImagenBase64     TEXT NULL,
    ImagenTipo       VARCHAR(40) NULL,    -- ej. image/jpeg

    -- Flujo de trabajo
    Estado           VARCHAR(20) NOT NULL DEFAULT 'Enviado'
                     CONSTRAINT CK_HojaConsumo_Estado
                     CHECK (Estado IN ('Enviado','En revisión','Creando TR','Finalizada','Error')),

    -- Resultado de la creación de TR (lo llena Bodega en una fase posterior)
    ResultadoTR      JSONB NULL,          -- { "tr": [...], "trabajos": [...] }

    -- Auditoría
    CreadoPor        VARCHAR(200) NULL,   -- nombre visible del usuario
    CreadoPorEmail   VARCHAR(200) NULL,   -- correo (para filtrar "mis hojas")
    FechaCreacion    TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    ModificadoPor    VARCHAR(200) NULL,
    FechaModificacion TIMESTAMP(0) NULL
);
CREATE INDEX IF NOT EXISTS IX_HojaConsumo_FechaCreacion ON dbo.HojaConsumo (FechaCreacion);
CREATE INDEX IF NOT EXISTS IX_HojaConsumo_Estado        ON dbo.HojaConsumo (Estado);
CREATE INDEX IF NOT EXISTS IX_HojaConsumo_CreadoPorEmail ON dbo.HojaConsumo (CreadoPorEmail);

/* ---------------------------------------------------------------------------
   Detalle de la hoja de consumo (LÍNEAS)  — relación uno-a-muchos
   --------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo.HojaConsumoDetalle (
    Id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HojaConsumoId     INT NOT NULL REFERENCES dbo.HojaConsumo(Id) ON DELETE CASCADE,
    Linea             INT NULL,               -- orden de la línea en la hoja
    Codigo            VARCHAR(60)  NULL,
    NumeroEquipo      VARCHAR(60)  NULL,
    Descripcion       VARCHAR(400) NULL,
    Und               INT NULL,
    ReposicionAnaquel INT NULL,
    NumeroLote        VARCHAR(80)  NULL       -- lo completa Bodega
);
CREATE INDEX IF NOT EXISTS IX_HojaConsumoDetalle_HojaId ON dbo.HojaConsumoDetalle (HojaConsumoId);

/* ---------------------------------------------------------------------------
   Vista para los grids: encabezado + usuario + cantidad de líneas de detalle
   (sin traer la imagen base64, para que el listado sea liviano)
   --------------------------------------------------------------------------- */
CREATE OR REPLACE VIEW dbo.vHojaConsumo AS
SELECT h.Id,
       h.NumeroHoja,
       h.NumeroDocumento,
       h.Regimen,
       h.Paciente,
       h.Cirujano,
       h.Instrumentista,
       h.Diagnostico,
       h.Estado,
       h.CreadoPor,
       h.CreadoPorEmail,
       h.FechaCreacion,
       (SELECT COUNT(*) FROM dbo.HojaConsumoDetalle d WHERE d.HojaConsumoId = h.Id) AS CantidadLineas
FROM dbo.HojaConsumo h;

/* ============================================================================
   FIN. Verificación rápida (opcional):
     SELECT Nombre FROM cat.Rol ORDER BY Id;
     SELECT * FROM dbo.vHojaConsumo ORDER BY FechaCreacion DESC;
   ============================================================================ */
