/* ============================================================================
   HDT · Hojas de Consumo — Crear Trabajos en Dynamics (Fase 1)
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   Ejecutar DESPUÉS de 01..04:  psql "<cadena-de-conexion>" -f 05_Dynamics.sql
   ----------------------------------------------------------------------------
   IDEMPOTENTE y NO destructivo: se puede re-ejecutar sin borrar datos.

   Contenido:
     1. Consecutivo: número de negocio autoincremental en el encabezado de la
        hoja, que INICIA EN 3000. Es el valor que se envía como "Consecutivo"
        al flujo de Power Automate. (El Id interno de la hoja se mantiene aparte
        y es el que se usa para navegar entre pantallas.)
     2. DynamicsLocation: URL de seguimiento cuando el flujo responde 202
        (asíncrono, procesos que tardan más de ~2 min). No se expone al navegador.
     3. dbo.DynamicsTrabajo: una fila por proceso devuelto por el endpoint
        (Reposición Bandeja, Facturación, Nutricare al Anaquel, Pedido Pendiente…),
        que alimenta la pantalla "Histórico de trabajos en Dynamics".
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------- 1. Consecutivo (inicia en 3000) ---------- */
CREATE SEQUENCE IF NOT EXISTS dbo.seq_consecutivo AS INT START WITH 3000 INCREMENT BY 1 MINVALUE 3000;

ALTER TABLE dbo.HojaConsumo ADD COLUMN IF NOT EXISTS Consecutivo INT;

/* Backfill de hojas existentes, en orden de Id, para que todas tengan Consecutivo. */
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT Id FROM dbo.HojaConsumo WHERE Consecutivo IS NULL ORDER BY Id LOOP
        UPDATE dbo.HojaConsumo SET Consecutivo = nextval('dbo.seq_consecutivo') WHERE Id = r.Id;
    END LOOP;
END $$;

/* A partir de ahora, cada hoja nueva recibe el siguiente Consecutivo automáticamente. */
ALTER TABLE dbo.HojaConsumo ALTER COLUMN Consecutivo SET DEFAULT nextval('dbo.seq_consecutivo');
CREATE UNIQUE INDEX IF NOT EXISTS UX_HojaConsumo_Consecutivo ON dbo.HojaConsumo (Consecutivo);

/* ---------- 2. URL de seguimiento del flujo asíncrono (202) ---------- */
ALTER TABLE dbo.HojaConsumo ADD COLUMN IF NOT EXISTS DynamicsLocation TEXT;

/* ---------- 3. Trabajos creados en Dynamics (histórico) ---------- */
CREATE TABLE IF NOT EXISTS dbo.DynamicsTrabajo (
    Id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HojaConsumoId INT NOT NULL REFERENCES dbo.HojaConsumo(Id) ON DELETE CASCADE,
    IdProceso     VARCHAR(80)  NULL,   -- ej. TR-018174 / HDTRB-2002
    IdHojaConsumo VARCHAR(60)  NULL,   -- el que devuelve el endpoint (se muestra en el grid)
    Proceso       VARCHAR(160) NULL,   -- ej. Facturacion, Nutricare al Anaquel, Pedido Pendiente
    Estado        VARCHAR(200) NULL,   -- ej. Trabajo Creado / No tiene productos por reponer
    FechaCreacion TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);
CREATE INDEX IF NOT EXISTS IX_DynamicsTrabajo_Hoja ON dbo.DynamicsTrabajo (HojaConsumoId);

/* ============================================================================
   FIN. Verificación rápida (opcional):
     SELECT Id, Consecutivo, Estado FROM dbo.HojaConsumo ORDER BY Id;
     SELECT * FROM dbo.DynamicsTrabajo ORDER BY FechaCreacion DESC;
   ============================================================================ */
