/* ============================================================================
   HDT · Hojas de Consumo — Pedido Pendiente (Fase 2)
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   Ejecutar DESPUÉS de 01..05:  psql "<cadena-de-conexion>" -f 06_PedidoPendiente.sql
   ----------------------------------------------------------------------------
   IDEMPOTENTE y NO destructivo: se puede re-ejecutar sin borrar datos.

   Guarda los productos que el flujo de Dynamics devuelve en el proceso
   "Pedido Pendiente" (atributo "Productos"). La pantalla "Pedido Pendiente"
   los lista y permite registrar envíos parciales al anaquel.

   Nota: al volver a crear los trabajos de una hoja, la API reemplaza los
   pedidos de esa hoja (y sus envíos, por el ON DELETE CASCADE).
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------- Pedido pendiente (una fila por producto) ---------- */
CREATE TABLE IF NOT EXISTS dbo.PedidoPendiente (
    Id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HojaConsumoId     INT NOT NULL REFERENCES dbo.HojaConsumo(Id) ON DELETE CASCADE,
    IdProducto        VARCHAR(60)  NULL,        -- Código (alias en la UI)
    Lote              VARCHAR(80)  NULL,
    Descripcion       VARCHAR(400) NULL,
    CantidadTotal     INT NOT NULL DEFAULT 0,   -- Cantidad (alias en la UI)
    ReposicionAnaquel INT NOT NULL DEFAULT 0,   -- Reposición (alias en la UI)
    Ubicacion         VARCHAR(100) NULL,        -- Bandeja (alias en la UI)
    CantidadEnviada   INT NOT NULL DEFAULT 0,   -- acumulado enviado (arranca en 0)
    Estado            VARCHAR(20) NOT NULL DEFAULT 'Por enviar'
                      CONSTRAINT CK_PedidoPendiente_Estado
                      CHECK (Estado IN ('Por enviar','Enviado')),
    FechaCreacion     TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);
CREATE INDEX IF NOT EXISTS IX_PedidoPendiente_Hoja ON dbo.PedidoPendiente (HojaConsumoId);

/* ---------- Envíos al anaquel (histórico por pedido) ---------- */
CREATE TABLE IF NOT EXISTS dbo.PedidoPendienteEnvio (
    Id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PedidoPendienteId INT NOT NULL REFERENCES dbo.PedidoPendiente(Id) ON DELETE CASCADE,
    CantidadEnviada   INT NOT NULL,            -- cantidad de este envío (> 0)
    Usuario           VARCHAR(200) NULL,       -- usuario de la app que registró el envío
    FechaHora         TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);
CREATE INDEX IF NOT EXISTS IX_PPEnvio_Pedido ON dbo.PedidoPendienteEnvio (PedidoPendienteId);

/* ============================================================================
   FIN. Verificación rápida (opcional):
     SELECT * FROM dbo.PedidoPendiente ORDER BY Id DESC;
     SELECT * FROM dbo.PedidoPendienteEnvio ORDER BY FechaHora DESC;
   ============================================================================ */
