/* ============================================================================
   HDT · Hojas de Consumo — Cirugías programadas (calendario)  (Fase 7)
   Ejecutar DESPUÉS de 01..10:  node run-db.js
   ----------------------------------------------------------------------------
   Cirugía programada (base del calendario). La hoja de consumo puede quedar
   asociada a una cirugía (CirugiaId). Campos según el formato del INS + el
   formulario de planeación quirúrgica.
   Idempotente: seguro de re-ejecutar.
   ============================================================================ */

CREATE TABLE IF NOT EXISTS dbo.Cirugia (
    Id                       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FechaCirugia             DATE NULL,
    HoraInicio               VARCHAR(8) NULL,      -- 'HH:MM'
    HoraFin                  VARCHAR(8) NULL,
    Tiempo                   VARCHAR(40) NULL,     -- ej. '2 Hora(s)'
    Ubicacion                VARCHAR(200) NULL,    -- sala / centro
    Identificacion           VARCHAR(60) NULL,
    Paciente                 VARCHAR(200) NULL,
    Regimen                  VARCHAR(60) NULL,
    FechaAccidente           DATE NULL,
    NumeroCaso               VARCHAR(60) NULL,
    Cirugia                  VARCHAR(400) NULL,    -- procedimiento
    Cirujano                 VARCHAR(200) NULL,
    Observacion              VARCHAR(1000) NULL,
    RequerimientoQuirurgico  VARCHAR(2000) NULL,
    Estado                   VARCHAR(20) NOT NULL DEFAULT 'Programada'
                             CONSTRAINT CK_Cirugia_Estado
                             CHECK (Estado IN ('Programada','Realizada','Cancelada')),
    CreadoPor                VARCHAR(200) NULL,
    CreadoPorEmail           VARCHAR(200) NULL,
    FechaCreacion            TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);
CREATE INDEX IF NOT EXISTS IX_Cirugia_Fecha ON dbo.Cirugia (FechaCirugia);

-- Enlace hoja de consumo -> cirugía.
ALTER TABLE dbo.HojaConsumo ADD COLUMN IF NOT EXISTS CirugiaId INT NULL;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hoja_cirugia') THEN
    ALTER TABLE dbo.HojaConsumo
      ADD CONSTRAINT FK_Hoja_Cirugia FOREIGN KEY (CirugiaId) REFERENCES dbo.Cirugia(Id);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS IX_HojaConsumo_Cirugia ON dbo.HojaConsumo (CirugiaId);
