/* ============================================================
   22_HospitalCatalogo.sql
   Catálogo de hospitales para el mantenimiento del módulo de
   Solicitud de Equipo.

   Origen: lista de hospitales del formulario de SharePoint (58 filas).
   Nada referenciaba hospitales antes de esta tabla, así que la carga se
   consolida ahora, que es cuando sale gratis.

   Consolidación: los nombres que son el mismo lugar escrito de varias
   formas quedan en un solo registro. Regla aplicada: gana el nombre más
   completo y la provincia sale del miembro que la tenga poblada. El
   detalle de qué nombre absorbió a cuál está al final del archivo.

   Los nombres se cargan tal como venían (solo se recortan espacios). Las
   tildes que faltan y los nombres mal escritos se corrigen desde la
   pantalla: para eso existe.

   Aplicar a mano con psql, antes del push.
   ============================================================ */

BEGIN;

CREATE TABLE IF NOT EXISTS cat.Hospital (
    Id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre             VARCHAR(200) NOT NULL,
    Provincia          VARCHAR(40)  NULL,
    Activo             BOOLEAN      NOT NULL DEFAULT TRUE,
    CreadoPor          VARCHAR(200) NULL,
    ActualizadoPor     VARCHAR(200) NULL,
    FechaActualizacion TIMESTAMP(0) NULL
);

/* Provincia: lista cerrada. La API ya normaliza la capitalización; esto es
   la red de seguridad para que no entre una variante por otra vía. */
ALTER TABLE cat.Hospital DROP CONSTRAINT IF EXISTS CK_Hospital_Provincia;
ALTER TABLE cat.Hospital ADD  CONSTRAINT CK_Hospital_Provincia
      CHECK (Provincia IS NULL OR Provincia IN ('San José', 'Alajuela', 'Cartago', 'Heredia', 'Guanacaste', 'Puntarenas', 'Limón'));

/* Esto es lo que evita que el problema se repita: dos hospitales no pueden
   tener el mismo nombre ignorando mayúsculas y espacios. Sin este índice, la
   lista vuelve a llenarse de «Hospital México» repetidos. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_Hospital_Nombre
    ON cat.Hospital (UPPER(TRIM(Nombre)));


/* ---------- Carga ---------- */

INSERT INTO cat.Hospital (Nombre, Provincia, Activo, CreadoPor, FechaActualizacion) VALUES
  ('Hospital Enrique Baltodano de Liberia', 'Guanacaste', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Centro Nacional de Rehabilitación CENARE', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Centro Oncológico Costarricense', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Clinica Zahha', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Rafael Angel Calderon Guardia', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital CIMA / San José', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Clinica Biblica / Lindora', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Clinica Biblica / San José', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital de Guapiles', 'Limón', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Nacional de Niños', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital del Trauma INS', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Escalante Pradilla / Perez Zeledon', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Hotel La Catolica', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital La Anexion de Nicoya', 'Guanacaste', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Max Peralta de Cartago', 'Cartago', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Metropolitano / Lindora', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Metropolitano / San José', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital México', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Monseñor Sanabria de Puntarenas', 'Puntarenas', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital San Juan de Dios', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital San Vicente de Paúl de Heredia', 'Heredia', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Tony Facio de Limon', 'Limón', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Universitario UNIBE', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Centro Quirurgico Ambulatorio RQ / Grecia', 'Alajuela', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Universal Cartago', 'Cartago', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Las Américas', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital San Francisco de Asis Grecia', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Tomas Casas', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Manuel Mora de Golfito', 'Puntarenas', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Ciudad Nelly', 'Puntarenas', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital San Vito Juana Pirola', 'Puntarenas', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospitales Varios', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('MAGNA Medica', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital San Rafael de Alajuela', 'Alajuela', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Prueba Desarrollo (Favor omitir)', NULL, FALSE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Aura Surgical Center', 'San José', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Carlos Luis Valverde Vega/San Ramón', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Nutricare', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Clínica Dr. Arias', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital William Allen Taylor', 'Cartago', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Max Terán Valls', 'Puntarenas', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital San Carlos', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Clinica Biblica aleste', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Hospital Metropolitano/Plaza Lincoln', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Nuestra Señora de los Ángeles', 'Cartago', TRUE, 'Carga SharePoint', (now() at time zone 'utc')),
  ('Infinitum Clínica Chavarría Estrada', NULL, TRUE, 'Carga SharePoint', (now() at time zone 'utc'))
ON CONFLICT DO NOTHING;


/* ---------- Qué se consolidó ----------

   Hospital CIMA / San José
       absorbio: Hospital CIMA San José
   Hospital Universitario UNIBE
       absorbio: Unibe
   MAGNA Medica
       absorbio: Magna
   Hospital Rafael Angel Calderon Guardia
       absorbio: Hospital calderon guardia
   Aura Surgical Center  [VERIFICAR]
       absorbio: Aura medica
   Hospital Hotel La Catolica
       absorbio: Hospital la catolica
   Nutricare  [VERIFICAR]
       absorbio: Oficina nutricare
   Hospital del Trauma INS
       absorbio: Hospital del trauma
       absorbio: Hospital Trauma
   Hospital Manuel Mora de Golfito
       absorbio: Hospital de Golfito
   Hospital México
       absorbio: Hospital México (repetido exacto)
       absorbio: Hospital México (repetido exacto)

   Los marcados [VERIFICAR] se consolidaron por indicación, pero podrían ser
   dos lugares distintos. Si lo son, se separan desde la pantalla creando el
   segundo registro.

   ---------- Lo que NO se tocó ----------
   Estos se dejaron como estaban porque corregirlos es criterio de Bodega,
   y la pantalla permite hacerlo en un par de clics:

     - Hospital San Francisco de Asis Grecia: dice San José, pero Grecia
       es Alajuela.
     - Hospital Tomas Casas: dice San José, pero está en Ciudad Cortés,
       Osa, Puntarenas.
     - 12 hospitales quedaron sin provincia.
     - Nutricare, Oficina nutricare y Hospitales Varios no son hospitales,
       pero entran ACTIVOS: si Bodega los usa como destino, desactivarlos le
       quitaría una opción. Se desactivan con un clic si no sirven.
     - Estos parecen sucursales distintas del mismo grupo y se dejaron
       separados a propósito: Clinica Biblica (San José / Lindora / al este)
       y Metropolitano (San José / Lindora / Plaza Lincoln).
*/

COMMIT;
