/* ============================================================
   23_Notificacion.sql
   Cuentas de correo que reciben aviso por cada evento del proceso
   de Solicitud de Equipo.

   La tabla arranca vacía: las cuentas se cargan desde la pantalla
   de Mantenimiento > Notificaciones.

   Aplicar a mano con psql, antes del push.
   ============================================================ */

BEGIN;

CREATE TABLE IF NOT EXISTS cat.Notificacion (
    Id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email              VARCHAR(200) NOT NULL,
    Solicitud          BOOLEAN NOT NULL DEFAULT FALSE,   -- Solicitud de equipo
    Alistado           BOOLEAN NOT NULL DEFAULT FALSE,   -- Equipo alistado
    Devolucion         BOOLEAN NOT NULL DEFAULT FALSE,   -- Devolución de equipo
    Liberado           BOOLEAN NOT NULL DEFAULT FALSE,   -- Equipo liberado
    CreadoPor          VARCHAR(200) NULL,
    ActualizadoPor     VARCHAR(200) NULL,
    FechaActualizacion TIMESTAMP(0) NULL
);

/* Una cuenta suscrita a nada no tiene sentido y ademas ensuciaria el
   listado de destinatarios. La API valida lo mismo antes de guardar; esto
   es la red de seguridad. */
ALTER TABLE cat.Notificacion DROP CONSTRAINT IF EXISTS CK_Notificacion_AlMenosUno;
ALTER TABLE cat.Notificacion ADD  CONSTRAINT CK_Notificacion_AlMenosUno
      CHECK (Solicitud OR Alistado OR Devolucion OR Liberado);

/* El correo no se puede repetir, ignorando mayúsculas y espacios. Sin esto
   una misma persona recibiría el aviso dos veces. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_Notificacion_Email
    ON cat.Notificacion (LOWER(TRIM(Email)));

COMMIT;
