/* ============================================================
   24_SolicitudEquipo.sql
   Solicitud de Equipo: encabezado, detalle de bandejas y el
   consecutivo del código ORT.

   Las tablas arrancan vacías.

   Aplicar a mano con psql, antes del push.
   ============================================================ */

BEGIN;

/* Consecutivo propio. No se reutiliza dbo.ConfiguracionConsecutivo porque esa
   tabla es de una sola fila (CHECK Id = 1) y pertenece a las hojas de consumo.
   Una SEQUENCE ademas no se pisa entre usuarios concurrentes. */
CREATE SEQUENCE IF NOT EXISTS dbo.SolicitudEquipoSeq START 1;

CREATE TABLE IF NOT EXISTS dbo.SolicitudEquipo (
    Id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Codigo             VARCHAR(40)  NOT NULL,
    Estado             VARCHAR(20)  NOT NULL DEFAULT 'Borrador',
    HospitalId         INT          NULL,
    Hospital           VARCHAR(200) NULL,   -- nombre al momento de la solicitud
    Cirugia            VARCHAR(400) NULL,
    FechaCirugia       DATE         NULL,
    HoraCirugia        VARCHAR(5)   NULL,   -- 'HH:MM'
    Cirujano           VARCHAR(200) NULL,
    PacienteCedula     VARCHAR(60)  NULL,
    PacienteNombre     VARCHAR(200) NULL,
    FechaEntrega       DATE         NULL,   -- opcional
    HoraEntrega        VARCHAR(5)   NULL,   -- opcional
    Observaciones      VARCHAR(1000) NULL,  -- opcional
    CreadoPor          VARCHAR(200) NULL,
    CreadoPorEmail     VARCHAR(200) NULL,
    FechaCreacion      TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    FechaEnvio         TIMESTAMP(0) NULL,
    ActualizadoPor     VARCHAR(200) NULL,
    FechaActualizacion TIMESTAMP(0) NULL
);

ALTER TABLE dbo.SolicitudEquipo DROP CONSTRAINT IF EXISTS CK_SolicitudEquipo_Estado;
ALTER TABLE dbo.SolicitudEquipo ADD  CONSTRAINT CK_SolicitudEquipo_Estado
      CHECK (Estado IN ('Borrador','Enviada'));

CREATE UNIQUE INDEX IF NOT EXISTS UX_SolicitudEquipo_Codigo
    ON dbo.SolicitudEquipo (UPPER(TRIM(Codigo)));

CREATE INDEX IF NOT EXISTS IX_SolicitudEquipo_Estado
    ON dbo.SolicitudEquipo (Estado, Id DESC);

/* El hospital se referencia por Id y ademas se guarda el nombre. Si manana
   Bodega corrige el nombre en el catalogo, las solicitudes ya enviadas
   conservan el texto con el que se enviaron. ON DELETE SET NULL por si acaso:
   la pantalla de Hospitales no borra, desactiva. */
ALTER TABLE dbo.SolicitudEquipo DROP CONSTRAINT IF EXISTS FK_SolicitudEquipo_Hospital;
ALTER TABLE dbo.SolicitudEquipo ADD  CONSTRAINT FK_SolicitudEquipo_Hospital
      FOREIGN KEY (HospitalId) REFERENCES cat.Hospital(Id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS dbo.SolicitudEquipoDetalle (
    Id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SolicitudId  INT NOT NULL,
    EquipoCodigo VARCHAR(40)  NOT NULL,   -- cat.Equipo.Codigo
    Demarcado    VARCHAR(60)  NULL,       -- 'NUT-0001330' para mostrar
    Descripcion  VARCHAR(300) NULL
);

/* Borrar la solicitud se lleva su detalle. Solo se pueden borrar los
   borradores, asi que no hay historico en riesgo. */
ALTER TABLE dbo.SolicitudEquipoDetalle DROP CONSTRAINT IF EXISTS FK_SolicitudDetalle_Solicitud;
ALTER TABLE dbo.SolicitudEquipoDetalle ADD  CONSTRAINT FK_SolicitudDetalle_Solicitud
      FOREIGN KEY (SolicitudId) REFERENCES dbo.SolicitudEquipo(Id) ON DELETE CASCADE;

/* La misma bandeja no se agrega dos veces a una solicitud. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_SolicitudDetalle_Bandeja
    ON dbo.SolicitudEquipoDetalle (SolicitudId, UPPER(TRIM(EquipoCodigo)));

COMMIT;
