/* ============================================================
   27_SolicitudAlisto.sql
   Alistado de Bodega: qué componentes de cada bandeja ya se
   apartaron para una solicitud.

   Una fila = un componente marcado. Desmarcar borra la fila, así que
   la tabla no guarda «falsos» y el porcentaje sale de un COUNT.

   El porcentaje se calcula por componente, uno vale uno: una línea de
   12 tornillos pesa igual que una de 1. Es lo que calza con marcar
   componente por componente y lo que el compañero puede verificar
   de un vistazo.

   Aplicar a mano con psql, antes del push.
   ============================================================ */

BEGIN;

/* El estado En Preparación entra al catálogo: la solicitud pasa ahí en
   cuanto Bodega guarda el primer check. No se revierte sola aunque se
   desmarque todo — el trabajo ya empezó. */
ALTER TABLE dbo.SolicitudEquipo DROP CONSTRAINT IF EXISTS CK_SolicitudEquipo_Estado;
ALTER TABLE dbo.SolicitudEquipo ADD  CONSTRAINT CK_SolicitudEquipo_Estado
      CHECK (Estado IN ('Borrador','Enviada','En Preparación'));

CREATE TABLE IF NOT EXISTS dbo.SolicitudAlisto (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SolicitudId    INT          NOT NULL,
    EquipoCodigo   VARCHAR(40)  NOT NULL,   -- bandeja dentro de la solicitud
    ProductoCodigo VARCHAR(60)  NOT NULL,   -- componente de cat.EquipoProducto
    AlistadoPor    VARCHAR(200) NULL,
    FechaAlisto    TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);

ALTER TABLE dbo.SolicitudAlisto DROP CONSTRAINT IF EXISTS FK_SolicitudAlisto_Solicitud;
ALTER TABLE dbo.SolicitudAlisto ADD  CONSTRAINT FK_SolicitudAlisto_Solicitud
      FOREIGN KEY (SolicitudId) REFERENCES dbo.SolicitudEquipo(Id) ON DELETE CASCADE;

/* Un componente no se marca dos veces en la misma bandeja de la misma
   solicitud. Sin esto, dos pestañas abiertas inflarían el porcentaje. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_SolicitudAlisto
    ON dbo.SolicitudAlisto (SolicitudId, UPPER(TRIM(EquipoCodigo)), UPPER(TRIM(ProductoCodigo)));

CREATE INDEX IF NOT EXISTS IX_SolicitudAlisto_Solicitud
    ON dbo.SolicitudAlisto (SolicitudId);

COMMIT;
