/* ============================================================
   32_EquipoFoto.sql
   Fotografías de referencia del catálogo de bandejas.

   Una bandeja tiene de 2 a 9 recipientes y cada uno se
   fotografía aparte, así que la tabla admite VARIAS fotos por
   bandeja, con rótulo y orden.

   El contenido va en base64 en una columna TEXT, igual que
   dbo.HojaConsumoSellada. Es a propósito: no mete una
   dependencia nueva en api/package.json —que sigue con solo
   @azure/functions y pg— ni obliga a administrar una cuenta de
   almacenamiento. El frontend reduce cada imagen a 1600 px de
   lado largo y la recomprime a JPEG antes de subirla, así que
   una foto entra con ~130 KB y no con los 5 MB de la cámara.

   PARA QUÉ SIRVE, hoy mismo y sin nada más:
   Bodega abre la bandeja en Mantenimiento y ve cómo debería
   verse. Y quien tenga que corregir el catálogo —hay 59
   discrepancias medidas entre lo impreso en las bandejas y
   cat.EquipoProducto— puede mirar la foto al lado del contenido
   registrado, que hoy no se puede hacer en ninguna pantalla.

   La foto se cuelga de cat.Equipo por su código, que es la
   llave primaria. ON DELETE CASCADE: si se borra una bandeja
   del catálogo, sus fotos se van con ella.

   IDEMPOTENTE y NO destructiva: seguro de re-ejecutar.
   Aplicar a mano con psql, antes del push.
   ============================================================ */

BEGIN;

CREATE TABLE IF NOT EXISTS cat.EquipoFoto (
    Id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EquipoCodigo  VARCHAR(40)  NOT NULL,
    /* Qué se ve en la foto: «Recipiente 1», «Tapa», «Bandeja de
       tornillos». Opcional: una galería sin rótulos también sirve,
       y obligarlo haría que nadie suba nada. */
    Rotulo        VARCHAR(100) NULL,
    /* Para ordenar la galería a mano. Empatados, manda el Id, que
       es el orden en que se subieron. */
    Orden         INT          NOT NULL DEFAULT 0,
    Nombre        VARCHAR(260) NULL,      -- nombre del archivo original
    Tipo          VARCHAR(60)  NOT NULL,  -- MIME; solo imágenes (lo valida la API)
    Bytes         INT          NULL,      -- tamaño aproximado ya decodificado
    Contenido     TEXT         NOT NULL,  -- la imagen en base64, sin el prefijo data:
    Usuario       VARCHAR(200) NOT NULL,
    UsuarioEmail  VARCHAR(200) NULL,
    FechaHora     TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);

ALTER TABLE cat.EquipoFoto DROP CONSTRAINT IF EXISTS FK_EquipoFoto_Equipo;
ALTER TABLE cat.EquipoFoto ADD  CONSTRAINT FK_EquipoFoto_Equipo
      FOREIGN KEY (EquipoCodigo) REFERENCES cat.Equipo(Codigo) ON DELETE CASCADE;

/* La galería de una bandeja, en su orden. */
CREATE INDEX IF NOT EXISTS IX_EquipoFoto_Equipo
    ON cat.EquipoFoto (EquipoCodigo, Orden, Id);

/* La misma foto no se sube dos veces a la misma bandeja. El índice va sobre el
   nombre del archivo y el tamaño, no sobre el contenido: un índice sobre una
   columna TEXT de 200 KB no entra en una página de Postgres. No es una
   garantía fuerte —dos fotos distintas con el mismo nombre y tamaño son
   posibles— pero atrapa el caso real, que es volver a correr la carga inicial
   o tocar «Subir» dos veces. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_EquipoFoto_Archivo
    ON cat.EquipoFoto (EquipoCodigo, COALESCE(Nombre,''), COALESCE(Bytes,0));

COMMIT;

/* ============================================================
   FIN. Verificación (sin traer el base64, que es enorme):

     SELECT f.EquipoCodigo, e.Demarcado, e.Nombre,
            COUNT(*) AS fotos, round(SUM(f.Bytes)/1024.0) AS kb
       FROM cat.EquipoFoto f
       JOIN cat.Equipo e ON e.Codigo = f.EquipoCodigo
      GROUP BY 1,2,3 ORDER BY 1;

   Cuánto pesa la tabla:
     SELECT pg_size_pretty(pg_total_relation_size('cat.EquipoFoto'));

   Bandejas del catálogo que todavía NO tienen foto (hoy son 106 de 118):
     SELECT e.Codigo, e.Demarcado, e.Nombre
       FROM cat.Equipo e
      WHERE NOT EXISTS (SELECT 1 FROM cat.EquipoFoto f WHERE f.EquipoCodigo = e.Codigo)
      ORDER BY 1;
   ============================================================ */
SELECT COUNT(*) AS fotos_de_bandeja FROM cat.EquipoFoto;
