/* ============================================================
   33_SolicitudValidacion.sql
   Validación de la bandeja alistada, con veredicto automático.

   CÓMO FUNCIONA
   Al subir cada foto de la entrega, la API la manda a Azure AI
   Document Intelligence y guarda el TEXTO que leyó. Al tocar
   «Validar», ese texto se compara contra el de las fotos de
   referencia del catálogo (cat.EquipoFoto, migración 32) y sale
   una de tres respuestas:

     Correcta               el texto de la bandeja física
                            corresponde al de la que pide la
                            solicitud.
     Incorrecta             corresponde mejor al de OTRA bandeja,
                            y se dice cuál.
     No puedo determinarlo  no se leyó suficiente texto, o la
                            diferencia con la segunda candidata
                            es demasiado chica para afirmar nada.

   POR QUÉ TRES Y NO DOS, con números. Se midieron 13 bandejas
   fotografiadas contra las 118 del catálogo. No existe un umbral
   que separe limpio: con el corte en 0,20 acepta 12 de 13
   correctas pero deja pasar 7 bandejas ajenas; con el corte en
   0,30 rechaza 4 buenas y todavía deja pasar 2. Las
   distribuciones se solapan —la correcta va de 0,108 a 0,855 y
   el mejor impostor llega a 0,694—. Un binario obligado tendría
   que mentir en uno de los dos sentidos. «No puedo determinarlo»
   es la respuesta honesta cuando el dato no alcanza, y sale
   seguido: es lo esperable en las bandejas de instrumental, que
   no traen códigos impresos.

   NINGÚN VEREDICTO BLOQUEA EL DESPACHO. Una persona puede
   confirmar o desmentir cualquiera de los tres desde la
   comparación a pantalla completa, y eso queda registrado con su
   nombre y hora. La marca manual es DISTINTA de la automática a
   propósito: dentro de tres meses tiene que poder saberse si la
   bandeja la aprobó el sistema o la aprobó alguien mirando.

   Aplicar a mano con psql, antes del push.
   ============================================================ */

BEGIN;

/* ------------------------------------------------------------------
   El texto leído de cada foto de REFERENCIA del catálogo.
   Se guarda una sola vez, cuando la foto se sube: sin esto habría que
   releer las 51 fotos de referencia en cada validación, que son 51
   llamadas a Azure por cada bandeja que se valide.
   ------------------------------------------------------------------ */
ALTER TABLE cat.EquipoFoto ADD COLUMN IF NOT EXISTS TextoOcr  TEXT         NULL;
ALTER TABLE cat.EquipoFoto ADD COLUMN IF NOT EXISTS FechaOcr  TIMESTAMP(0) NULL;
ALTER TABLE cat.EquipoFoto ADD COLUMN IF NOT EXISTS ErrorOcr  VARCHAR(300) NULL;

/* Las que todavía no se leyeron. La API las va leyendo cuando hacen falta. */
CREATE INDEX IF NOT EXISTS IX_EquipoFoto_SinOcr
    ON cat.EquipoFoto (EquipoCodigo) WHERE TextoOcr IS NULL;

/* ------------------------------------------------------------------
   Fotos de la entrega: de ESTA solicitud y ESTA bandeja. Distintas de
   cat.EquipoFoto, que son las de referencia del catálogo.
   ------------------------------------------------------------------ */
CREATE TABLE IF NOT EXISTS dbo.SolicitudFoto (
    Id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SolicitudId   INT          NOT NULL,
    EquipoCodigo  VARCHAR(40)  NOT NULL,
    Nombre        VARCHAR(260) NULL,
    Tipo          VARCHAR(60)  NOT NULL,
    Bytes         INT          NULL,
    Contenido     TEXT         NOT NULL,   -- base64, igual que en la 32
    TextoOcr      TEXT         NULL,       -- lo que leyó Document Intelligence
    ErrorOcr      VARCHAR(300) NULL,       -- por qué no se pudo leer, si falló
    Usuario       VARCHAR(200) NOT NULL,
    UsuarioEmail  VARCHAR(200) NULL,
    FechaHora     TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);

ALTER TABLE dbo.SolicitudFoto DROP CONSTRAINT IF EXISTS FK_SolicitudFoto_Solicitud;
ALTER TABLE dbo.SolicitudFoto ADD  CONSTRAINT FK_SolicitudFoto_Solicitud
      FOREIGN KEY (SolicitudId) REFERENCES dbo.SolicitudEquipo(Id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS IX_SolicitudFoto_Bandeja
    ON dbo.SolicitudFoto (SolicitudId, UPPER(TRIM(EquipoCodigo)), Id);

/* ------------------------------------------------------------------
   El veredicto: una fila por bandeja de la solicitud.
   ------------------------------------------------------------------ */
CREATE TABLE IF NOT EXISTS dbo.SolicitudVerificacion (
    Id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SolicitudId     INT          NOT NULL,
    EquipoCodigo    VARCHAR(40)  NOT NULL,
    Resultado       VARCHAR(24)  NOT NULL,   -- Correcta / Incorrecta / No puedo determinarlo
    /* De dónde salió: lo calculó el sistema, o lo dijo una persona mirando.
       Son dos cosas distintas y tienen que poder distinguirse después. */
    Origen          VARCHAR(12)  NOT NULL,   -- Automatico / Persona
    Motivo          VARCHAR(600) NULL,       -- por qué, en llano
    Puntaje         NUMERIC(5,3) NULL,       -- contra la bandeja pedida
    /* A qué se parece más, cuando no es la pedida. Es la respuesta a la
       primera pregunta que se hace Bodega frente a un «Incorrecta»: ¿cuál es? */
    CandidatoCodigo VARCHAR(40)  NULL,
    CandidatoPuntaje NUMERIC(5,3) NULL,
    /* El color de demarcación, opcional. Es lo único que separa dos bandejas
       de contenido idéntico: el texto de las dos es el mismo. */
    ColorObservado  VARCHAR(60)  NULL,
    ColorCatalogo   VARCHAR(60)  NULL,
    Nota            VARCHAR(400) NULL,
    Usuario         VARCHAR(200) NOT NULL,
    UsuarioEmail    VARCHAR(200) NULL,
    FechaHora       TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc')
);

ALTER TABLE dbo.SolicitudVerificacion DROP CONSTRAINT IF EXISTS CK_SolicitudVerificacion_Resultado;
ALTER TABLE dbo.SolicitudVerificacion ADD  CONSTRAINT CK_SolicitudVerificacion_Resultado
      CHECK (Resultado IN ('Correcta','Incorrecta','No puedo determinarlo'));

ALTER TABLE dbo.SolicitudVerificacion DROP CONSTRAINT IF EXISTS CK_SolicitudVerificacion_Origen;
ALTER TABLE dbo.SolicitudVerificacion ADD  CONSTRAINT CK_SolicitudVerificacion_Origen
      CHECK (Origen IN ('Automatico','Persona'));

ALTER TABLE dbo.SolicitudVerificacion DROP CONSTRAINT IF EXISTS FK_SolicitudVerificacion_Solicitud;
ALTER TABLE dbo.SolicitudVerificacion ADD  CONSTRAINT FK_SolicitudVerificacion_Solicitud
      FOREIGN KEY (SolicitudId) REFERENCES dbo.SolicitudEquipo(Id) ON DELETE CASCADE;

/* Una bandeja tiene un veredicto por solicitud: volver a validar reescribe la
   fila. Sin este índice, dos pestañas abiertas dejarían dos veredictos y
   ninguno sería «el» de la entrega. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_SolicitudVerificacion
    ON dbo.SolicitudVerificacion (SolicitudId, UPPER(TRIM(EquipoCodigo)));

/* ------------------------------------------------------------------
   Cómo salió la solicitud, estampado al despachar.

   NO es un estado nuevo del ciclo de vida, y es a propósito: un quinto valor
   en CK_SolicitudEquipo_Estado que significa lo mismo —el equipo salió—
   obligaría a tocar las cejillas de los dos roles, los filtros, SOL_DESPACHADA
   en todas las comparaciones de solo lectura, el evento de notificación y los
   impresos, y cada filtro futuro tendría que acordarse de incluir los dos.
   Como columna aparte es una pastilla al lado del estado y una columna
   filtrable, y no se toca nada de lo que ya funciona.

   Se ESTAMPA al despachar y no se calcula en vivo porque es evidencia: si
   mañana alguien valida lo que faltaba, un despacho de la semana pasada no
   puede volverse «Validada» retroactivamente.
   ------------------------------------------------------------------ */
ALTER TABLE dbo.SolicitudEquipo ADD COLUMN IF NOT EXISTS ValidacionBandejas VARCHAR(20) NULL;

ALTER TABLE dbo.SolicitudEquipo DROP CONSTRAINT IF EXISTS CK_SolicitudEquipo_Validacion;
ALTER TABLE dbo.SolicitudEquipo ADD  CONSTRAINT CK_SolicitudEquipo_Validacion
      CHECK (ValidacionBandejas IS NULL OR ValidacionBandejas IN ('Validada','Parcial','Sin validar'));

COMMIT;

/* ============================================================
   FIN. Verificación:

     SELECT EquipoCodigo, COUNT(*) AS fotos,
            COUNT(TextoOcr) AS leidas, COUNT(ErrorOcr) AS con_error
       FROM cat.EquipoFoto GROUP BY 1 ORDER BY 1;

     SELECT s.Codigo, v.EquipoCodigo, v.Resultado, v.Origen,
            v.Puntaje, v.CandidatoCodigo, v.CandidatoPuntaje, v.Usuario
       FROM dbo.SolicitudVerificacion v
       JOIN dbo.SolicitudEquipo s ON s.Id = v.SolicitudId
      ORDER BY v.Id DESC LIMIT 20;

   Bandejas que NO van a poder validarse automáticamente porque no tienen
   fotos de referencia leídas (hoy son 106 de 118):
     SELECT e.Codigo, e.Demarcado, e.Nombre
       FROM cat.Equipo e
      WHERE NOT EXISTS (SELECT 1 FROM cat.EquipoFoto f
                         WHERE f.EquipoCodigo = e.Codigo AND f.TextoOcr IS NOT NULL)
      ORDER BY 1;
   ============================================================ */
SELECT (SELECT COUNT(*) FROM cat.EquipoFoto WHERE TextoOcr IS NOT NULL) AS referencias_leidas,
       (SELECT COUNT(*) FROM dbo.SolicitudFoto)                          AS fotos_de_entrega,
       (SELECT COUNT(*) FROM dbo.SolicitudVerificacion)                  AS veredictos;
